#!/usr/bin/env python3
"""
=============================================================
  BACKTEST ENGINE v1.1 (SSL-patched)
  --------------------
  Backtests the multi-indicator trading strategy.

  Usage:
    python backtest_engine.py                       # Default: SPY, 2y, $10k
    python backtest_engine.py --symbol AAPL          # Custom ticker
    python backtest_engine.py --symbol NVDA --period 5y --capital 50000
    python backtest_engine.py --all                  # Backtest entire watchlist

  Author : Lemon Leong (generated by Copilot)
  Date   : 2026-05-15
  License: MIT
=============================================================
"""

import argparse
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

# ── FIX: Corporate SSL (Micron network) ─────────────────
# Monkey-patches curl_cffi to skip SSL certificate verification.
# Required when running behind corporate firewalls that intercept HTTPS.
from curl_cffi import requests as _curl_requests
_original_init = _curl_requests.Session.__init__
def _patched_init(self, *args, **kwargs):
    kwargs["verify"] = False
    _original_init(self, *args, **kwargs)
_curl_requests.Session.__init__ = _patched_init
import warnings
warnings.filterwarnings("ignore", message=".*Unverified HTTPS.*")
# ─────────────────────────────────────────────────────────

# ═══════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════

EMA_FAST = 9
EMA_SLOW = 21
RSI_PERIOD = 14
RSI_BUY_RANGE = (40, 70)
RSI_SELL_RANGE = (30, 60)
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
VOLUME_MA_PERIOD = 20
SIGNAL_THRESHOLD = 0.8

INITIAL_CAPITAL = 10_000
COMMISSION_PCT = 0.001
SLIPPAGE_PCT = 0.0005
POSITION_SIZE_PCT = 0.95
RISK_FREE_RATE = 0.05

WATCHLIST = [
    "ADM", "DE", "MOS", "CF", "WEAT", "DBA",
    "FSLR", "ENPH", "AWK", "XLU",
    "AAPL", "MSFT", "NVDA", "TSLA", "SPY",
]


def calculate_indicators(df):
    df = df.copy()
    df["EMA_fast"] = df["Close"].ewm(span=EMA_FAST, adjust=False).mean()
    df["EMA_slow"] = df["Close"].ewm(span=EMA_SLOW, adjust=False).mean()
    delta = df["Close"].diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.ewm(com=RSI_PERIOD - 1, min_periods=RSI_PERIOD).mean()
    avg_loss = loss.ewm(com=RSI_PERIOD - 1, min_periods=RSI_PERIOD).mean()
    rs = avg_gain / avg_loss
    df["RSI"] = 100 - (100 / (1 + rs))
    ema_f = df["Close"].ewm(span=MACD_FAST, adjust=False).mean()
    ema_s = df["Close"].ewm(span=MACD_SLOW, adjust=False).mean()
    df["MACD_line"] = ema_f - ema_s
    df["MACD_signal"] = df["MACD_line"].ewm(span=MACD_SIGNAL, adjust=False).mean()
    df["MACD_hist"] = df["MACD_line"] - df["MACD_signal"]
    df["BB_middle"] = df["Close"].rolling(BB_PERIOD).mean()
    bb_std = df["Close"].rolling(BB_PERIOD).std()
    df["BB_upper"] = df["BB_middle"] + BB_STD * bb_std
    df["BB_lower"] = df["BB_middle"] - BB_STD * bb_std
    df["Volume_MA"] = df["Volume"].rolling(VOLUME_MA_PERIOD).mean()
    return df


def generate_signals(df):
    df = df.copy()
    ema_bull = df["EMA_fast"] > df["EMA_slow"]
    rsi_buy = (df["RSI"] >= RSI_BUY_RANGE[0]) & (df["RSI"] <= RSI_BUY_RANGE[1])
    macd_bull = df["MACD_hist"] > 0
    bb_not_upper = df["Close"] < df["BB_upper"] * 0.99
    vol_above = df["Volume"] > df["Volume_MA"]
    buy_score = (ema_bull.astype(int) + rsi_buy.astype(int) +
                 macd_bull.astype(int) + bb_not_upper.astype(int) +
                 vol_above.astype(int)) / 5

    ema_bear = df["EMA_fast"] < df["EMA_slow"]
    rsi_sell = (df["RSI"] >= RSI_SELL_RANGE[0]) & (df["RSI"] <= RSI_SELL_RANGE[1])
    macd_bear = df["MACD_hist"] < 0
    bb_not_lower = df["Close"] > df["BB_lower"] * 1.01
    sell_score = (ema_bear.astype(int) + rsi_sell.astype(int) +
                  macd_bear.astype(int) + bb_not_lower.astype(int) +
                  vol_above.astype(int)) / 5

    df["Signal"] = 0
    df.loc[buy_score >= SIGNAL_THRESHOLD, "Signal"] = 1
    df.loc[sell_score >= SIGNAL_THRESHOLD, "Signal"] = -1
    return df


def run_backtest(df, symbol, initial_capital=INITIAL_CAPITAL):
    df = df.copy().dropna()
    capital = initial_capital
    position = 0
    entry_price = 0.0
    entry_date = None
    portfolio_values = []
    trades = []

    for i in range(len(df)):
        row = df.iloc[i]
        date = df.index[i]
        price = row["Close"]
        signal = row["Signal"]

        if signal == 1 and position == 0:
            buy_price = price * (1 + SLIPPAGE_PCT)
            investable = capital * POSITION_SIZE_PCT
            commission = investable * COMMISSION_PCT
            shares = int((investable - commission) / buy_price)
            if shares > 0:
                cost = shares * buy_price + commission
                capital -= cost
                position = shares
                entry_price = buy_price
                entry_date = date

        elif signal == -1 and position > 0:
            sell_price = price * (1 - SLIPPAGE_PCT)
            revenue = position * sell_price
            commission = revenue * COMMISSION_PCT
            capital += revenue - commission
            pnl = (sell_price - entry_price) * position - commission
            pnl_pct = (sell_price / entry_price - 1) * 100
            holding_days = (date - entry_date).days if entry_date else 0
            trades.append({
                "Symbol": symbol, "Entry_Date": entry_date, "Exit_Date": date,
                "Entry_Price": round(entry_price, 2), "Exit_Price": round(sell_price, 2),
                "Shares": position, "PnL": round(pnl, 2), "PnL_Pct": round(pnl_pct, 2),
                "Holding_Days": holding_days, "Win": pnl > 0,
            })
            position = 0
            entry_price = 0.0
            entry_date = None

        portfolio_val = capital + position * price if position > 0 else capital
        portfolio_values.append(portfolio_val)

    df["Portfolio"] = portfolio_values
    df["BuyHold"] = initial_capital * (df["Close"] / df["Close"].iloc[0])
    return df, trades


def calculate_metrics(df, trades, initial_capital=INITIAL_CAPITAL):
    portfolio = df["Portfolio"].values
    buyhold = df["BuyHold"].values
    n_days = len(df)
    n_years = n_days / 252

    total_return = (portfolio[-1] / initial_capital - 1) * 100
    bh_return = (buyhold[-1] / initial_capital - 1) * 100
    cagr = ((portfolio[-1] / initial_capital) ** (1 / n_years) - 1) * 100 if n_years > 0 else 0.0
    bh_cagr = ((buyhold[-1] / initial_capital) ** (1 / n_years) - 1) * 100 if n_years > 0 else 0.0

    daily_returns = pd.Series(portfolio).pct_change().dropna()
    sharpe = ((daily_returns.mean() - RISK_FREE_RATE/252) / daily_returns.std() * np.sqrt(252)) if daily_returns.std() > 0 else 0.0
    downside = daily_returns[daily_returns < 0]
    sortino = ((daily_returns.mean() - RISK_FREE_RATE/252) / downside.std() * np.sqrt(252)) if len(downside) > 0 and downside.std() > 0 else 0.0

    peak = pd.Series(portfolio).cummax()
    drawdown = (pd.Series(portfolio) - peak) / peak * 100
    max_dd = drawdown.min()
    calmar = cagr / abs(max_dd) if max_dd != 0 else 0.0

    n_trades = len(trades)
    if n_trades > 0:
        wins = [t for t in trades if t["Win"]]
        losses = [t for t in trades if not t["Win"]]
        win_rate = len(wins) / n_trades * 100
        avg_win = np.mean([t["PnL_Pct"] for t in wins]) if wins else 0.0
        avg_loss = np.mean([t["PnL_Pct"] for t in losses]) if losses else 0.0
        total_win_pnl = sum(t["PnL"] for t in wins)
        total_loss_pnl = abs(sum(t["PnL"] for t in losses))
        profit_factor = total_win_pnl / total_loss_pnl if total_loss_pnl > 0 else float("inf")
        avg_holding = np.mean([t["Holding_Days"] for t in trades])
        best_trade = max(t["PnL_Pct"] for t in trades)
        worst_trade = min(t["PnL_Pct"] for t in trades)
    else:
        win_rate = avg_win = avg_loss = profit_factor = avg_holding = 0.0
        best_trade = worst_trade = 0.0

    volatility = daily_returns.std() * np.sqrt(252) * 100

    metrics = {
        "Total Return (%)": round(total_return, 2),
        "Buy & Hold Return (%)": round(bh_return, 2),
        "CAGR (%)": round(cagr, 2),
        "B&H CAGR (%)": round(bh_cagr, 2),
        "Sharpe Ratio": round(sharpe, 2),
        "Sortino Ratio": round(sortino, 2),
        "Max Drawdown (%)": round(max_dd, 2),
        "Calmar Ratio": round(calmar, 2),
        "Volatility (%)": round(volatility, 2),
        "Total Trades": n_trades,
        "Win Rate (%)": round(win_rate, 2),
        "Avg Win (%)": round(avg_win, 2),
        "Avg Loss (%)": round(avg_loss, 2),
        "Profit Factor": round(profit_factor, 2),
        "Best Trade (%)": round(best_trade, 2),
        "Worst Trade (%)": round(worst_trade, 2),
        "Avg Holding (days)": round(avg_holding, 1),
        "Final Capital ($)": round(portfolio[-1], 2),
        "Starting Capital ($)": initial_capital,
    }
    return metrics, drawdown


# ═══════════════════════════════════════════════════════════
# CHARTS
# ═══════════════════════════════════════════════════════════

def plot_equity_curve(df, metrics, symbol):
    fig, ax = plt.subplots(figsize=(14, 6))
    ax.plot(df.index, df["Portfolio"], label="Strategy", color="#2196F3", linewidth=2)
    ax.plot(df.index, df["BuyHold"], label="Buy & Hold", color="#9E9E9E", linewidth=1.5, linestyle="--")
    ax.fill_between(df.index, df["Portfolio"], alpha=0.1, color="#2196F3")
    ax.set_title(f"Equity Curve - {symbol}\n"
                 f"Strategy: {metrics['Total Return (%)']:+.2f}%  |  "
                 f"Buy & Hold: {metrics['Buy & Hold Return (%)']:+.2f}%  |  "
                 f"Sharpe: {metrics['Sharpe Ratio']:.2f}", fontsize=13, fontweight="bold")
    ax.set_ylabel("Portfolio Value ($)")
    ax.set_xlabel("Date")
    ax.legend(loc="upper left")
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig("backtest_equity_curve.png", dpi=150)
    plt.close()
    print("  Chart saved: backtest_equity_curve.png")


def plot_drawdown(df, drawdown, symbol):
    fig, ax = plt.subplots(figsize=(14, 4))
    ax.fill_between(df.index, drawdown.values, 0, color="#F44336", alpha=0.4)
    ax.plot(df.index, drawdown.values, color="#F44336", linewidth=1)
    ax.set_title(f"Drawdown - {symbol}  |  Max: {drawdown.min():.2f}%", fontsize=13, fontweight="bold")
    ax.set_ylabel("Drawdown (%)")
    ax.set_xlabel("Date")
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig("backtest_drawdown.png", dpi=150)
    plt.close()
    print("  Chart saved: backtest_drawdown.png")


def plot_signals_on_price(df, trades, symbol):
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 9), height_ratios=[3, 1], sharex=True)
    ax1.plot(df.index, df["Close"], label="Close", color="#333", linewidth=1.5)
    ax1.plot(df.index, df["EMA_fast"], label=f"EMA {EMA_FAST}", color="#2196F3", linewidth=1, alpha=0.8)
    ax1.plot(df.index, df["EMA_slow"], label=f"EMA {EMA_SLOW}", color="#FF9800", linewidth=1, alpha=0.8)
    ax1.fill_between(df.index, df["BB_upper"], df["BB_lower"], alpha=0.08, color="#9C27B0")
    for t in trades:
        ax1.scatter([t["Entry_Date"]], [t["Entry_Price"]], marker="^", color="#4CAF50", s=100, zorder=5)
        ax1.scatter([t["Exit_Date"]], [t["Exit_Price"]], marker="v", color="#F44336", s=100, zorder=5)
    ax1.set_title(f"Price Chart with Signals - {symbol}  (^ Buy  v Sell)", fontsize=13, fontweight="bold")
    ax1.set_ylabel("Price ($)")
    ax1.legend(loc="upper left", fontsize=9)
    ax1.grid(True, alpha=0.3)
    ax2.plot(df.index, df["RSI"], color="#673AB7", linewidth=1)
    ax2.axhline(70, color="#F44336", linestyle="--", linewidth=0.8, alpha=0.5)
    ax2.axhline(30, color="#4CAF50", linestyle="--", linewidth=0.8, alpha=0.5)
    ax2.set_ylabel("RSI")
    ax2.set_xlabel("Date")
    ax2.set_ylim(0, 100)
    ax2.grid(True, alpha=0.3)
    ax2.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig("backtest_signals.png", dpi=150)
    plt.close()
    print("  Chart saved: backtest_signals.png")


def plot_trade_distribution(trades, symbol):
    if not trades:
        return
    pnls = [t["PnL_Pct"] for t in trades]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p <= 0]
    fig, ax = plt.subplots(figsize=(10, 5))
    all_bins = np.linspace(min(pnls)-1, max(pnls)+1, 20)
    if wins:
        ax.hist(wins, bins=all_bins, color="#4CAF50", alpha=0.7, label=f"Wins ({len(wins)})", edgecolor="white")
    if losses:
        ax.hist(losses, bins=all_bins, color="#F44336", alpha=0.7, label=f"Losses ({len(losses)})", edgecolor="white")
    ax.axvline(0, color="#333", linewidth=1.5)
    ax.axvline(np.mean(pnls), color="#2196F3", linewidth=1.5, linestyle="--", label=f"Avg: {np.mean(pnls):.2f}%")
    ax.set_title(f"Trade P&L Distribution - {symbol}", fontsize=13, fontweight="bold")
    ax.set_xlabel("Return (%)")
    ax.set_ylabel("Number of Trades")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig("backtest_distribution.png", dpi=150)
    plt.close()
    print("  Chart saved: backtest_distribution.png")


def plot_monthly_returns(df, symbol):
    daily_ret = df["Portfolio"].pct_change()
    monthly_ret = daily_ret.resample("ME").apply(lambda x: (1 + x).prod() - 1) * 100
    monthly_df = pd.DataFrame({"Year": monthly_ret.index.year, "Month": monthly_ret.index.month, "Return": monthly_ret.values})
    pivot = monthly_df.pivot_table(values="Return", index="Year", columns="Month", aggfunc="sum")
    month_names = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
    pivot.columns = [month_names[c-1] for c in pivot.columns]
    fig, ax = plt.subplots(figsize=(12, max(3, len(pivot)*1.0)))
    vals = pivot.values[~np.isnan(pivot.values)]
    vmax = max(abs(vals.min()), abs(vals.max()), 5) if len(vals) > 0 else 5
    im = ax.imshow(pivot.values, cmap=plt.cm.RdYlGn, aspect="auto", vmin=-vmax, vmax=vmax)
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, fontsize=10)
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index, fontsize=10)
    for i in range(len(pivot.index)):
        for j in range(len(pivot.columns)):
            val = pivot.values[i, j]
            if not np.isnan(val):
                color = "white" if abs(val) > vmax*0.6 else "black"
                ax.text(j, i, f"{val:.1f}%", ha="center", va="center", fontsize=9, fontweight="bold", color=color)
    ax.set_title(f"Monthly Returns Heatmap (%) - {symbol}", fontsize=13, fontweight="bold")
    plt.colorbar(im, ax=ax, label="Return (%)", shrink=0.8)
    plt.tight_layout()
    plt.savefig("backtest_monthly_returns.png", dpi=150)
    plt.close()
    print("  Chart saved: backtest_monthly_returns.png")


def print_report(metrics, symbol, period):
    print("\n" + "=" * 62)
    print(f"  BACKTEST REPORT - {symbol}")
    print(f"  Period: {period}  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    print("=" * 62)
    print(f"\n  {'Starting Capital:':<25} ${metrics['Starting Capital ($)']:>12,.2f}")
    print(f"  {'Final Capital:':<25} ${metrics['Final Capital ($)']:>12,.2f}")
    print(f"  {'Total Return:':<25} {metrics['Total Return (%)']:>12.2f}%")
    print(f"  {'Buy & Hold Return:':<25} {metrics['Buy & Hold Return (%)']:>12.2f}%")
    print(f"  {'CAGR:':<25} {metrics['CAGR (%)']:>12.2f}%")
    print(f"  {'B&H CAGR:':<25} {metrics['B&H CAGR (%)']:>12.2f}%")
    print(f"\n  {'Sharpe Ratio:':<25} {metrics['Sharpe Ratio']:>12.2f}")
    print(f"  {'Sortino Ratio:':<25} {metrics['Sortino Ratio']:>12.2f}")
    print(f"  {'Max Drawdown:':<25} {metrics['Max Drawdown (%)']:>12.2f}%")
    print(f"  {'Calmar Ratio:':<25} {metrics['Calmar Ratio']:>12.2f}")
    print(f"  {'Volatility:':<25} {metrics['Volatility (%)']:>12.2f}%")
    print(f"\n  {'Total Trades:':<25} {metrics['Total Trades']:>12}")
    print(f"  {'Win Rate:':<25} {metrics['Win Rate (%)']:>12.2f}%")
    print(f"  {'Avg Win:':<25} {metrics['Avg Win (%)']:>12.2f}%")
    print(f"  {'Avg Loss:':<25} {metrics['Avg Loss (%)']:>12.2f}%")
    print(f"  {'Profit Factor:':<25} {metrics['Profit Factor']:>12.2f}")
    print(f"  {'Best Trade:':<25} {metrics['Best Trade (%)']:>12.2f}%")
    print(f"  {'Worst Trade:':<25} {metrics['Worst Trade (%)']:>12.2f}%")
    print(f"  {'Avg Holding:':<25} {metrics['Avg Holding (days)']:>12.1f} days")
    strat = metrics["Total Return (%)"]
    bh = metrics["Buy & Hold Return (%)"]
    print(f"\n  Verdict: ", end="")
    if strat > bh:
        print(f"Strategy BEATS Buy & Hold by {strat - bh:.2f}%")
    else:
        print(f"Strategy trails Buy & Hold by {bh - strat:.2f}%")
    print("=" * 62)


# ═══════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Trading Strategy Backtester v1.1 (SSL-patched)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python backtest_engine.py                       # SPY, 2 years
  python backtest_engine.py --symbol AAPL         # Apple, 2 years
  python backtest_engine.py --symbol NVDA --period 5y --capital 50000
  python backtest_engine.py --all                 # All 15 tickers
        """
    )
    parser.add_argument("--symbol", type=str, default="SPY", help="Ticker symbol (default: SPY)")
    parser.add_argument("--period", type=str, default="2y", help="Data period (default: 2y)")
    parser.add_argument("--capital", type=float, default=10000, help="Initial capital (default: 10000)")
    parser.add_argument("--all", action="store_true", help="Backtest entire watchlist")
    args = parser.parse_args()

    symbols = WATCHLIST if args.all else [args.symbol.upper()]
    all_metrics = []

    for sym in symbols:
        print(f"\n{'='*60}")
        print(f"  Backtesting: {sym} | Period: {args.period} | Capital: ${args.capital:,.2f}")
        print(f"{'='*60}")

        try:
            ticker = yf.Ticker(sym)
            df = ticker.history(period=args.period, interval="1d")

            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)

            if df.empty or len(df) < 30:
                print(f"  Skipping {sym} - insufficient data ({len(df)} rows)")
                continue

            print(f"  Loaded {len(df)} bars: {df.index[0].strftime('%Y-%m-%d')} to {df.index[-1].strftime('%Y-%m-%d')}")

            df = calculate_indicators(df)
            df = generate_signals(df)

            buy_count = (df["Signal"] == 1).sum()
            sell_count = (df["Signal"] == -1).sum()
            print(f"  Signals found: {buy_count} BUY, {sell_count} SELL")

            df, trades = run_backtest(df, sym, args.capital)
            metrics, drawdown = calculate_metrics(df, trades, args.capital)
            metrics["Symbol"] = sym
            all_metrics.append(metrics)

            print_report(metrics, sym, args.period)

            if len(symbols) == 1:
                print("\n  Generating charts...")
                plot_equity_curve(df, metrics, sym)
                plot_drawdown(df, drawdown, sym)
                plot_signals_on_price(df, trades, sym)
                plot_trade_distribution(trades, sym)
                plot_monthly_returns(df, sym)

                if trades:
                    trades_exp = []
                    for t in trades:
                        te = t.copy()
                        te["Entry_Date"] = str(te["Entry_Date"])[:10]
                        te["Exit_Date"] = str(te["Exit_Date"])[:10]
                        trades_exp.append(te)
                    pd.DataFrame(trades_exp).to_csv("backtest_trades.csv", index=False)
                    print(f"  Trades exported: backtest_trades.csv ({len(trades)} trades)")

                pd.DataFrame([metrics]).to_csv("backtest_metrics.csv", index=False)
                df[["Close","Portfolio","BuyHold","Signal","RSI","MACD_hist"]].to_csv("backtest_daily.csv")
                print("  Metrics + daily data exported")

        except Exception as e:
            print(f"  ERROR on {sym}: {e}")
            continue

    if len(all_metrics) > 1:
        summary_df = pd.DataFrame(all_metrics)
        summary_df.to_csv("backtest_summary.csv", index=False)
        print(f"\n{'='*80}")
        print("  WATCHLIST BACKTEST SUMMARY")
        print(f"{'='*80}")
        display_cols = ["Symbol", "Total Return (%)", "CAGR (%)", "Sharpe Ratio",
                        "Max Drawdown (%)", "Win Rate (%)", "Profit Factor", "Total Trades"]
        avail_cols = [c for c in display_cols if c in summary_df.columns]
        print(summary_df[avail_cols].to_string(index=False))
        print(f"\n  Summary saved: backtest_summary.csv")

    print(f"\nDone!")


if __name__ == "__main__":
    main()
