#!/usr/bin/env python3
"""
=============================================================
  TRADING SIGNAL DASHBOARD v2.2
  (v2.1 + fetch_history wrapper — fixes $nan MultiIndex issue)
  Author : Lemon Leong (generated by Copilot)
  Date   : 2026-05-15
=============================================================
"""

import json, os
from datetime import datetime, timezone, timedelta
import numpy as np, pandas as pd
import streamlit as st
import yfinance as yf
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── FIX: Corporate SSL (Micron network) ─────────────────
from curl_cffi import requests as _curl_requests
_original_init = _curl_requests.Session.__init__
def _patched_init(self, *args, **kwargs):
    kwargs["verify"] = False
    _original_init(self, *args, **kwargs)
_curl_requests.Session.__init__ = _patched_init
import warnings
warnings.filterwarnings("ignore", message=".*Unverified HTTPS.*")
# ─────────────────────────────────────────────────────────


CONFIG_FILE = "bot_config.json"
WATCHLIST_FILE = "watchlist.json"
DEFAULT_WATCHLIST = ["ADM","DE","MOS","CF","WEAT","DBA","FSLR","ENPH","AWK","XLU","AAPL","MSFT","NVDA","TSLA","SPY"]
DEFAULT_CONFIG = {"signal_threshold": 0.8, "supertrend_atr_period": 10, "supertrend_multiplier": 3.0}

def load_config():
    config = DEFAULT_CONFIG.copy()
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f: saved = json.load(f); config.update(saved)
        except: pass
    return config

def save_config(config):
    with open(CONFIG_FILE, "w") as f: json.dump(config, f, indent=2)

def load_watchlist():
    if os.path.exists(WATCHLIST_FILE):
        try:
            with open(WATCHLIST_FILE, "r") as f:
                data = json.load(f)
                if isinstance(data, list) and len(data) > 0:
                    return [t.upper().strip() for t in data if t.strip()]
        except: pass
    return DEFAULT_WATCHLIST.copy()

def save_watchlist(tickers):
    clean = [t.upper().strip() for t in tickers if t.strip()]
    seen = set(); unique = []
    for t in clean:
        if t not in seen: seen.add(t); unique.append(t)
    with open(WATCHLIST_FILE, "w") as f: json.dump(unique, f, indent=2)
    return unique

def get_market_status():
    et = timezone(timedelta(hours=-4))
    now_et = datetime.now(et)
    wd = now_et.weekday(); t = now_et.hour * 60 + now_et.minute
    if wd >= 5: return "CLOSED (Weekend)", "red"
    elif t < 240: return "CLOSED", "red"
    elif t < 570: return "PRE-MARKET", "orange"
    elif t < 960: return "MARKET OPEN", "green"
    elif t < 1200: return "AFTER-HOURS", "orange"
    else: return "CLOSED", "red"

def get_live_price(sym):
    try:
        tk = yf.Ticker(sym)
        try:
            fi = tk.fast_info
            lp = getattr(fi, "last_price", None)
            if lp and lp > 0: return round(lp, 2), "live"
        except: pass
        try:
            info = tk.info
            for key in ["regularMarketPrice", "currentPrice", "previousClose"]:
                p = info.get(key)
                if p and p > 0: return round(p, 2), "info"
        except: pass
    except: pass
    return None, "unavailable"


# ══════════════════════════════════════════════════════════
# FETCH_HISTORY — Permanent fix for MultiIndex $nan issue
# ══════════════════════════════════════════════════════════

def fetch_history(symbol, **kwargs):
    """Bulletproof history fetch — works with ALL yfinance versions."""
    try:
        df = yf.download(symbol, progress=False, **kwargs)
    except:
        df = pd.DataFrame()
    if df.empty:
        try:
            df = yf.Ticker(symbol).history(**kwargs)
        except:
            return pd.DataFrame()
    # Fix MultiIndex columns
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.droplevel("Ticker")
    # Remove duplicate columns
    df = df.loc[:, ~df.columns.duplicated()]
    # Drop rows where Close is NaN (incomplete trading day)
    if "Close" in df.columns:
        df = df.dropna(subset=["Close"])
    return df

WATCHLIST = load_watchlist()
config = load_config()

st.set_page_config(page_title="Trading Signal Dashboard", page_icon="\U0001f4c8", layout="wide", initial_sidebar_state="expanded")

EMA_FAST=9; EMA_SLOW=21; RSI_PERIOD=14; BB_PERIOD=20; BB_STD=2
MACD_FAST=12; MACD_SLOW=26; MACD_SIGNAL=9; VOLUME_MA_PERIOD=20
ICHIMOKU_TENKAN=9; ICHIMOKU_KIJUN=26; ICHIMOKU_SENKOU_B=52
COMMISSION_PCT=0.001; SLIPPAGE_PCT=0.0005; POSITION_SIZE_PCT=0.95; RISK_FREE_RATE=0.05
SIGNALS_LOG = "signals_history.json"

# These will be set from sidebar
SUPERTREND_ATR_PERIOD = config["supertrend_atr_period"]
SUPERTREND_MULTIPLIER = config["supertrend_multiplier"]
SIGNAL_THRESHOLD = config["signal_threshold"]

def calculate_indicators(df, st_atr_period=None, st_multiplier=None):
    df = df.copy()
    _st_atr = st_atr_period if st_atr_period else SUPERTREND_ATR_PERIOD
    _st_mult = st_multiplier if st_multiplier else SUPERTREND_MULTIPLIER
    df["EMA_fast"] = df["Close"].ewm(span=EMA_FAST, adjust=False).mean()
    df["EMA_slow"] = df["Close"].ewm(span=EMA_SLOW, adjust=False).mean()
    delta = df["Close"].diff()
    gain = delta.where(delta > 0, 0.0); loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.ewm(com=RSI_PERIOD-1, min_periods=RSI_PERIOD).mean()
    avg_loss = loss.ewm(com=RSI_PERIOD-1, min_periods=RSI_PERIOD).mean()
    rs = avg_gain / avg_loss; df["RSI"] = 100 - (100 / (1 + rs))
    ema_fm = df["Close"].ewm(span=MACD_FAST, adjust=False).mean()
    ema_sm = df["Close"].ewm(span=MACD_SLOW, adjust=False).mean()
    df["MACD_line"] = ema_fm - ema_sm
    df["MACD_signal"] = df["MACD_line"].ewm(span=MACD_SIGNAL, adjust=False).mean()
    df["MACD_hist"] = df["MACD_line"] - df["MACD_signal"]
    df["BB_middle"] = df["Close"].rolling(BB_PERIOD).mean()
    bb_std = df["Close"].rolling(BB_PERIOD).std()
    df["BB_upper"] = df["BB_middle"] + BB_STD * bb_std
    df["BB_lower"] = df["BB_middle"] - BB_STD * bb_std
    df["Volume_MA"] = df["Volume"].rolling(VOLUME_MA_PERIOD).mean()
    tp = (df["High"] + df["Low"] + df["Close"]) / 3
    df["VWAP"] = (tp * df["Volume"]).cumsum() / df["Volume"].cumsum()
    h9 = df["High"].rolling(ICHIMOKU_TENKAN).max(); l9 = df["Low"].rolling(ICHIMOKU_TENKAN).min()
    df["Tenkan"] = (h9 + l9) / 2
    h26 = df["High"].rolling(ICHIMOKU_KIJUN).max(); l26 = df["Low"].rolling(ICHIMOKU_KIJUN).min()
    df["Kijun"] = (h26 + l26) / 2
    df["Senkou_A"] = ((df["Tenkan"] + df["Kijun"]) / 2).shift(ICHIMOKU_KIJUN)
    h52 = df["High"].rolling(ICHIMOKU_SENKOU_B).max(); l52 = df["Low"].rolling(ICHIMOKU_SENKOU_B).min()
    df["Senkou_B"] = ((h52 + l52) / 2).shift(ICHIMOKU_KIJUN)
    hl2 = (df["High"] + df["Low"]) / 2
    high_low = df["High"] - df["Low"]
    high_close = (df["High"] - df["Close"].shift()).abs()
    low_close = (df["Low"] - df["Close"].shift()).abs()
    true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    atr_st = true_range.rolling(_st_atr).mean()
    upper_band = hl2 + _st_mult * atr_st
    lower_band = hl2 - _st_mult * atr_st
    supertrend = pd.Series(index=df.index, dtype=float)
    direction = pd.Series(index=df.index, dtype=float)
    supertrend.iloc[0] = upper_band.iloc[0]; direction.iloc[0] = -1
    for i in range(1, len(df)):
        if pd.isna(upper_band.iloc[i]) or pd.isna(lower_band.iloc[i]):
            supertrend.iloc[i] = supertrend.iloc[i-1]; direction.iloc[i] = direction.iloc[i-1]; continue
        fl = lower_band.iloc[i] if (lower_band.iloc[i] > lower_band.iloc[i-1] or df["Close"].iloc[i-1] < lower_band.iloc[i-1]) else lower_band.iloc[i-1]
        fu = upper_band.iloc[i] if (upper_band.iloc[i] < upper_band.iloc[i-1] or df["Close"].iloc[i-1] > upper_band.iloc[i-1]) else upper_band.iloc[i-1]
        if supertrend.iloc[i-1] == fu:
            if df["Close"].iloc[i] > fu: supertrend.iloc[i] = fl; direction.iloc[i] = 1
            else: supertrend.iloc[i] = fu; direction.iloc[i] = -1
        else:
            if df["Close"].iloc[i] < fl: supertrend.iloc[i] = fu; direction.iloc[i] = -1
            else: supertrend.iloc[i] = fl; direction.iloc[i] = 1
    df["Supertrend"] = supertrend; df["ST_Direction"] = direction
    return df


# ── SIDEBAR ──
st.sidebar.title("Settings")
sel_sym = st.sidebar.selectbox("Ticker", WATCHLIST, index=0)
data_per = st.sidebar.selectbox("Period (Daily)", ["30d","60d","90d","6mo","1y"], index=2)

# ── Intraday Mode ──
st.sidebar.markdown("---")
st.sidebar.markdown("### Intraday Mode")
intraday_on = st.sidebar.checkbox("Enable Intraday Mode", value=False, key="intra_on")
if intraday_on:
    intra_interval = st.sidebar.selectbox("Interval", ["1m", "2m", "5m", "10m", "15m", "20m", "30m", "45m", "1h"], index=4, key="intra_int")
    intra_period = "60d" if intra_interval == "1h" else ("1d" if intra_interval in ["1m", "2m"] else "5d")
    st.sidebar.caption(f"Data: {intra_period} / {intra_interval}")
    ar = st.sidebar.checkbox("Auto-refresh (60s)", value=True, key="intra_ar")
    if ar:
        st.sidebar.info("Auto-refresh: ON (60s)")
    else:
        st.sidebar.caption("Auto-refresh OFF — refresh manually")
    with st.sidebar.expander("Intraday Params"):
        INTRA_ST_ATR = st.number_input("Intraday ST ATR", min_value=5, max_value=30, value=10, step=1, key="ist_atr")
        INTRA_ST_MULT = st.number_input("Intraday ST Mult", min_value=1.0, max_value=6.0, value=2.0, step=0.5, key="ist_mult",
            help="2.0 = tighter for intraday (vs 3.0 daily)")
        INTRA_THRESHOLD = st.slider("Intraday Threshold", 0.50, 1.00, 0.75, 0.05, key="ist_thr",
            help="0.75 = 6/8 indicators (slightly looser for intraday)")
        st.caption(f"Need {int(INTRA_THRESHOLD*8)}/8 indicators")
else:
    intra_interval = None; intra_period = None
    INTRA_ST_ATR = 10; INTRA_ST_MULT = 2.0; INTRA_THRESHOLD = 0.75
    ar = st.sidebar.checkbox("Auto-refresh (60s)", value=False)
    if ar: st.sidebar.info("Refreshes every 60s")

import time

# ── Strategy Settings (Daily) ──
st.sidebar.markdown("---")
st.sidebar.markdown("### Daily Strategy")
SIGNAL_THRESHOLD = st.sidebar.slider("Signal Threshold", 0.50, 1.00, config["signal_threshold"], 0.05, key="d_thr")
needed = int(SIGNAL_THRESHOLD * 8)
st.sidebar.caption(f"Need **{needed}/8** indicators ({SIGNAL_THRESHOLD:.0%})")
if SIGNAL_THRESHOLD != config["signal_threshold"]:
    config["signal_threshold"] = SIGNAL_THRESHOLD; save_config(config)

with st.sidebar.expander("Daily Supertrend Params"):
    SUPERTREND_ATR_PERIOD = st.number_input("ATR Period", min_value=5, max_value=30, value=config["supertrend_atr_period"], step=1, key="st_atr")
    SUPERTREND_MULTIPLIER = st.number_input("Multiplier", min_value=1.0, max_value=6.0, value=config["supertrend_multiplier"], step=0.5, key="st_mult")
    if SUPERTREND_ATR_PERIOD != config["supertrend_atr_period"] or SUPERTREND_MULTIPLIER != config["supertrend_multiplier"]:
        config["supertrend_atr_period"] = SUPERTREND_ATR_PERIOD
        config["supertrend_multiplier"] = SUPERTREND_MULTIPLIER
        save_config(config)

# ── Watchlist ──
st.sidebar.markdown("---")
st.sidebar.markdown("### Edit Watchlist")
st.sidebar.caption(f"Tracking {len(WATCHLIST)} tickers")
with st.sidebar.expander("Add / Remove"):
    ca1,ca2 = st.columns([3,1])
    with ca1: nt = st.text_input("Add", placeholder="e.g. AMZN", key="nt")
    with ca2: st.markdown("<br>", unsafe_allow_html=True); ab = st.button("Add", key="ab", use_container_width=True)
    if ab and nt.strip():
        tu=nt.upper().strip()
        if tu in WATCHLIST: st.warning(f"{tu} exists")
        else: WATCHLIST.append(tu); save_watchlist(WATCHLIST); st.success(f"Added {tu}!"); st.rerun()
    st.markdown("**Full list:**")
    wlt=st.text_area("Edit",value="\n".join(WATCHLIST),height=200,key="wle",label_visibility="collapsed")
    b1,b2=st.columns(2)
    with b1:
        if st.button("Save",key="sv",use_container_width=True):
            nl=[t.strip().upper() for t in wlt.strip().split("\n") if t.strip()]
            if nl: save_watchlist(nl); st.success(f"Saved {len(nl)}!"); st.rerun()
            else: st.error("Empty!")
    with b2:
        if st.button("Reset",key="rs",use_container_width=True):
            save_watchlist(DEFAULT_WATCHLIST); st.success("Reset!"); st.rerun()

# ── Backtest ──
st.sidebar.markdown("---")
st.sidebar.markdown("### Backtest")
bdi=WATCHLIST.index("SPY") if "SPY" in WATCHLIST else len(WATCHLIST)-1
bts=st.sidebar.selectbox("Ticker",WATCHLIST,index=bdi,key="bs")
btp=st.sidebar.selectbox("Period",["1y","2y","5y","max"],index=1,key="bp")
btc=st.sidebar.number_input("Capital ($)",min_value=1000,max_value=1000000,value=10000,step=1000,key="bc")


# ── SIGNAL FUNCTIONS ──

def compute_signal_score(df, threshold):
    if len(df) < 55: return "HOLD", 0.0
    la = df.iloc[-1]
    eb=la["EMA_fast"]>la["EMA_slow"]; ro=40<=la["RSI"]<=70; mo=la["MACD_hist"]>0
    bo=la["Close"]<la["BB_upper"]*0.99; vo=la["Volume"]>la["Volume_MA"] if la["Volume_MA"]>0 else False
    vb=la["Close"]>la["VWAP"] if pd.notna(la["VWAP"]) else False
    iok=pd.notna(la["Senkou_A"]) and pd.notna(la["Senkou_B"])
    if iok:
        ib=(la["Close"]>max(la["Senkou_A"],la["Senkou_B"])) and (la["Tenkan"]>la["Kijun"])
        ise=(la["Close"]<min(la["Senkou_A"],la["Senkou_B"])) and (la["Tenkan"]<la["Kijun"])
    else: ib=False; ise=False
    stb=la["ST_Direction"]==1 if pd.notna(la["ST_Direction"]) else False
    sts=la["ST_Direction"]==-1 if pd.notna(la["ST_Direction"]) else False
    bs=sum([eb,ro,mo,bo,vo,vb,ib,stb])/8
    ee=not eb; rs=30<=la["RSI"]<=60; ms=la["MACD_hist"]<0; bbs=la["Close"]>la["BB_lower"]*1.01
    vs=la["Close"]<la["VWAP"] if pd.notna(la["VWAP"]) else False
    ss=sum([ee,rs,ms,bbs,vo,vs,ise,sts])/8
    if bs >= threshold: return "BUY", bs
    elif ss >= threshold: return "SELL", ss
    return "HOLD", max(bs, ss)

def quick_signal_with_levels(df, threshold, live_price=None):
    if len(df) < 55: return "HOLD", 0.0, {}
    sig, conf = compute_signal_score(df, threshold)
    la = df.iloc[-1]
    stv = la["Supertrend"] if pd.notna(la["Supertrend"]) else 0
    entry = round(live_price, 2) if live_price and live_price > 0 else round(la["Close"], 2)
    levels = {}
    if sig == "BUY":
        sl = round(stv,2) if (pd.notna(stv) and stv>0 and stv<entry) else round(la["BB_lower"],2)
        risk = entry-sl
        if risk<=0: risk=entry*0.02; sl=round(entry-risk,2)
        t1=round(la["BB_upper"],2); t2=round(entry+2*risk,2)
        levels={"entry":entry,"stop_loss":sl,"target_1":t1,"target_2":t2,"risk_pct":round((entry-sl)/entry*100,2),"rr":round((t1-entry)/risk,2) if risk>0 else 0}
    elif sig == "SELL":
        sl = round(stv,2) if (pd.notna(stv) and stv>0 and stv>entry) else round(la["BB_upper"],2)
        risk = sl-entry
        if risk<=0: risk=entry*0.02; sl=round(entry+risk,2)
        t1=round(la["BB_lower"],2); t2=round(entry-2*risk,2)
        levels={"entry":entry,"stop_loss":sl,"target_1":t1,"target_2":t2,"risk_pct":round((sl-entry)/entry*100,2),"rr":round((entry-t1)/risk,2) if risk>0 else 0}
    return sig, conf, levels

def load_signal_history():
    if os.path.exists(SIGNALS_LOG):
        try:
            with open(SIGNALS_LOG, "r") as f: return json.load(f)
        except: pass
    return []


# ── CANDLESTICK CHART ──

def create_candlestick_chart(df, symbol, interval_label="Daily"):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.03,
                        row_heights=[0.75, 0.25], subplot_titles=[f"{symbol} — {interval_label}", "Volume"])
    fig.add_trace(go.Candlestick(x=df.index, open=df["Open"], high=df["High"], low=df["Low"], close=df["Close"],
                                  name="OHLC", increasing_line_color="#4CAF50", decreasing_line_color="#F44336"), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["EMA_fast"], name=f"EMA {EMA_FAST}", line=dict(color="#2196F3", width=1.2)), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["EMA_slow"], name=f"EMA {EMA_SLOW}", line=dict(color="#FF9800", width=1.2)), row=1, col=1)
    if "Supertrend" in df.columns:
        bull = df[df["ST_Direction"]==1]
        bear = df[df["ST_Direction"]==-1]
        if len(bull) > 0:
            fig.add_trace(go.Scatter(x=bull.index, y=bull["Supertrend"], name="ST Bull", mode="markers",
                                      marker=dict(color="#4CAF50", size=3)), row=1, col=1)
        if len(bear) > 0:
            fig.add_trace(go.Scatter(x=bear.index, y=bear["Supertrend"], name="ST Bear", mode="markers",
                                      marker=dict(color="#F44336", size=3)), row=1, col=1)
    if "VWAP" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["VWAP"], name="VWAP", line=dict(color="#9C27B0", width=1, dash="dot")), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["BB_upper"], name="BB Upper", line=dict(color="rgba(158,158,158,0.4)", width=0.8)), row=1, col=1)
    fig.add_trace(go.Scatter(x=df.index, y=df["BB_lower"], name="BB Lower", line=dict(color="rgba(158,158,158,0.4)", width=0.8),
                              fill="tonexty", fillcolor="rgba(158,158,158,0.05)"), row=1, col=1)
    colors = ["#4CAF50" if c >= o else "#F44336" for c, o in zip(df["Close"], df["Open"])]
    fig.add_trace(go.Bar(x=df.index, y=df["Volume"], name="Volume", marker_color=colors, opacity=0.6), row=2, col=1)
    if "Volume_MA" in df.columns:
        fig.add_trace(go.Scatter(x=df.index, y=df["Volume_MA"], name="Vol MA", line=dict(color="#FF9800", width=1)), row=2, col=1)
    fig.update_layout(height=600, xaxis_rangeslider_visible=False, template="plotly_white",
                      legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1, font=dict(size=10)),
                      margin=dict(l=50, r=20, t=40, b=20))
    fig.update_xaxes(showgrid=True, gridcolor="rgba(200,200,200,0.3)")
    fig.update_yaxes(showgrid=True, gridcolor="rgba(200,200,200,0.3)")
    return fig


# ── BACKTEST FUNCTIONS ──

def generate_backtest_signals(df):
    df = df.copy()
    eb=df["EMA_fast"]>df["EMA_slow"]; rb=(df["RSI"]>=40)&(df["RSI"]<=70); mb=df["MACD_hist"]>0
    bbu=df["Close"]<df["BB_upper"]*0.99; va=df["Volume"]>df["Volume_MA"]
    vb=df["Close"]>df["VWAP"]; ct=df[["Senkou_A","Senkou_B"]].max(axis=1)
    cb=df[["Senkou_A","Senkou_B"]].min(axis=1); ib=(df["Close"]>ct)&(df["Tenkan"]>df["Kijun"])
    sb=df["ST_Direction"]==1
    bsc=(eb.astype(int)+rb.astype(int)+mb.astype(int)+bbu.astype(int)+va.astype(int)+vb.astype(int)+ib.astype(int)+sb.astype(int))/8
    ee=df["EMA_fast"]<df["EMA_slow"]; rs=(df["RSI"]>=30)&(df["RSI"]<=60); ms=df["MACD_hist"]<0
    bbl=df["Close"]>df["BB_lower"]*1.01; vs=df["Close"]<df["VWAP"]
    ise=(df["Close"]<cb)&(df["Tenkan"]<df["Kijun"]); ss=df["ST_Direction"]==-1
    ssc=(ee.astype(int)+rs.astype(int)+ms.astype(int)+bbl.astype(int)+va.astype(int)+vs.astype(int)+ise.astype(int)+ss.astype(int))/8
    df["Signal"]=0; df.loc[bsc>=SIGNAL_THRESHOLD,"Signal"]=1; df.loc[ssc>=SIGNAL_THRESHOLD,"Signal"]=-1
    return df

def run_backtest_sim(df, sym, ic):
    df=df.copy().dropna(); cap=ic; pos=0; ep=0.0; ed=None; pv=[]; tr=[]
    for i in range(len(df)):
        r=df.iloc[i]; d=df.index[i]; p=r["Close"]; s=r["Signal"]
        if s==1 and pos==0:
            bp=p*(1+SLIPPAGE_PCT); inv=cap*POSITION_SIZE_PCT; cm=inv*COMMISSION_PCT; sh=int((inv-cm)/bp)
            if sh>0: cap-=sh*bp+cm; pos=sh; ep=bp; ed=d
        elif s==-1 and pos>0:
            sp=p*(1-SLIPPAGE_PCT); rv=pos*sp; cm=rv*COMMISSION_PCT; cap+=rv-cm
            pnl=(sp-ep)*pos-cm; pp=(sp/ep-1)*100; hd=(d-ed).days if ed else 0
            tr.append({"Symbol":sym,"Entry Date":str(ed)[:10],"Exit Date":str(d)[:10],"Entry Price":round(ep,2),
                "Exit Price":round(sp,2),"Shares":pos,"P&L ($)":round(pnl,2),"P&L (%)":round(pp,2),"Days Held":hd,"Result":"WIN" if pnl>0 else "LOSS"})
            pos=0; ep=0.0; ed=None
        pv.append(cap+pos*p if pos>0 else cap)
    df["Portfolio"]=pv; df["BuyHold"]=ic*(df["Close"]/df["Close"].iloc[0])
    return df, tr

def bt_metrics(df, tr, ic):
    p=df["Portfolio"].values; bh=df["BuyHold"].values; n=len(df); ny=n/252
    tr2=(p[-1]/ic-1)*100; bhr=(bh[-1]/ic-1)*100
    cagr=((p[-1]/ic)**(1/ny)-1)*100 if ny>0 else 0; bhc=((bh[-1]/ic)**(1/ny)-1)*100 if ny>0 else 0
    dr=pd.Series(p).pct_change().dropna()
    sh=((dr.mean()-RISK_FREE_RATE/252)/dr.std()*np.sqrt(252)) if dr.std()>0 else 0
    ds=dr[dr<0]; so=((dr.mean()-RISK_FREE_RATE/252)/ds.std()*np.sqrt(252)) if len(ds)>0 and ds.std()>0 else 0
    pk=pd.Series(p).cummax(); dd=(pd.Series(p)-pk)/pk*100; mdd=dd.min()
    cal=cagr/abs(mdd) if mdd!=0 else 0; nt=len(tr)
    if nt>0:
        w=[t for t in tr if t["Result"]=="WIN"]; l=[t for t in tr if t["Result"]=="LOSS"]
        wr=len(w)/nt*100; aw=np.mean([t["P&L (%)"] for t in w]) if w else 0; al=np.mean([t["P&L (%)"] for t in l]) if l else 0
        twp=sum(t["P&L ($)"] for t in w); tlp=abs(sum(t["P&L ($)"] for t in l))
        pf=twp/tlp if tlp>0 else float("inf"); ah=np.mean([t["Days Held"] for t in tr])
        bt=max(t["P&L (%)"] for t in tr); wt=min(t["P&L (%)"] for t in tr)
    else: wr=aw=al=pf=ah=bt=wt=0.0
    vol=dr.std()*np.sqrt(252)*100
    return {"Total Return (%)":round(tr2,2),"Buy & Hold Return (%)":round(bhr,2),"CAGR (%)":round(cagr,2),"B&H CAGR (%)":round(bhc,2),
        "Sharpe Ratio":round(sh,2),"Sortino Ratio":round(so,2),"Max Drawdown (%)":round(mdd,2),"Calmar Ratio":round(cal,2),
        "Volatility (%)":round(vol,2),"Total Trades":nt,"Win Rate (%)":round(wr,2),"Avg Win (%)":round(aw,2),
        "Avg Loss (%)":round(al,2),"Profit Factor":round(pf,2),"Best Trade (%)":round(bt,2),"Worst Trade (%)":round(wt,2),
        "Avg Holding (days)":round(ah,1),"Final Capital ($)":round(p[-1],2),"Starting Capital ($)":ic}, dd

@st.cache_data(ttl=300, show_spinner=False)
def run_full_backtest(sym, per, ic, threshold, st_atr, st_mult):
    df = fetch_history(sym, period=per, interval="1d")
    if df.empty or len(df)<55: return None,None,None,None
    df=calculate_indicators(df); df=generate_backtest_signals(df)
    df,tr=run_backtest_sim(df,sym,ic); m,dd=bt_metrics(df,tr,ic)
    return df,tr,m,dd


# ═══════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════

market_status, market_color = get_market_status()
needed = int(SIGNAL_THRESHOLD * 8)
mode_label = f"Intraday ({intra_interval})" if intraday_on else "Daily"

st.title("Trading Signal Dashboard")
refresh_status = "\U0001f504 Auto-refresh ON (60s)" if ar else "\u23f8\ufe0f Auto-refresh OFF"
st.caption(f"Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | {len(WATCHLIST)} tickers | Mode: {mode_label} | Threshold: {SIGNAL_THRESHOLD:.0%} | {refresh_status}")

tab1,tab2,tab3,tab4,tab5 = st.tabs(["Live Scanner","Chart Analysis","Signal History","Backtest","News"])


# ═══════════════════════════════════════════════════════════
# TAB 1: SCANNER
# ═══════════════════════════════════════════════════════════
with tab1:
    st.header("Watchlist Scanner")
    if market_color == "green": st.success(f"US Market: {market_status}")
    elif market_color == "orange": st.warning(f"US Market: {market_status}")
    else: st.info(f"US Market: {market_status}")

    if intraday_on:
        st.info(f"Dual mode: Daily signals + Intraday ({intra_interval}) confirmation")

    sd = []; pg = st.progress(0); sta = st.empty()
    for i, sym in enumerate(WATCHLIST):
        sta.text(f"Scanning {sym} ({i+1}/{len(WATCHLIST)})..."); pg.progress((i+1)/len(WATCHLIST))
        try:
            # Daily data — uses fetch_history (MultiIndex safe)
            df_d = fetch_history(sym, period="90d", interval="1d")
            if len(df_d) < 55: continue
            df_d = calculate_indicators(df_d)
            live_p, _ = get_live_price(sym)
            d_sig, d_conf, d_lv = quick_signal_with_levels(df_d, SIGNAL_THRESHOLD, live_p)
            la = df_d.iloc[-1]
            prev = df_d.iloc[-2] if len(df_d) > 1 else la
            daily_close = round(float(la["Close"]), 2)
            chg = ((float(la["Close"]) - float(prev["Close"])) / float(prev["Close"])) * 100
            std_dir = "Bullish" if pd.notna(la["ST_Direction"]) and float(la["ST_Direction"]) == 1 else "Bearish"
            ichi = "Above" if pd.notna(la["Senkou_A"]) and float(la["Close"]) > max(float(la["Senkou_A"]), float(la["Senkou_B"])) else ("Below" if pd.notna(la["Senkou_A"]) and float(la["Close"]) < min(float(la["Senkou_A"]), float(la["Senkou_B"])) else "In Cloud")
            if live_p and live_p > 0 and daily_close > 0:
                vs_close = round((live_p - daily_close) / daily_close * 100, 2)
            else:
                vs_close = 0.0
            if not live_p:
                live_p = daily_close
            row = {
                "Symbol": sym,
                "Live Price": live_p,
                "Close": daily_close,
                "vs Close": vs_close,
                "Daily Chg %": round(chg, 2),
                "Daily Signal": d_sig,
                "Daily Conf": round(d_conf * 100),
                "Conf_raw": d_conf,
                "RSI": round(float(la["RSI"]), 1),
                "Supertrend": std_dir,
                "Ichimoku": ichi,
                "Volume": int(float(la["Volume"])),
            }
            # Intraday signal — uses fetch_history (MultiIndex safe)
            if intraday_on:
                try:
                    df_i = fetch_history(sym, period=intra_period, interval=intra_interval)
                    if len(df_i) >= 55:
                        df_i = calculate_indicators(df_i, st_atr_period=INTRA_ST_ATR, st_multiplier=INTRA_ST_MULT)
                        i_sig, i_conf = compute_signal_score(df_i, INTRA_THRESHOLD)
                        row["Intraday Signal"] = i_sig
                        row["Intra Conf"] = round(i_conf * 100)
                    else:
                        row["Intraday Signal"] = "N/A"; row["Intra Conf"] = 0
                except:
                    row["Intraday Signal"] = "Error"; row["Intra Conf"] = 0

                ds = row["Daily Signal"]; iis = row["Intraday Signal"]
                if ds == "BUY" and iis == "BUY": row["Confirm"] = "CONFIRMED BUY"
                elif ds == "SELL" and iis == "SELL": row["Confirm"] = "CONFIRMED SELL"
                elif ds in ("BUY","SELL") and iis not in ("BUY","SELL"): row["Confirm"] = "DAILY ONLY"
                elif iis in ("BUY","SELL") and ds not in ("BUY","SELL"): row["Confirm"] = "INTRADAY ONLY"
                else: row["Confirm"] = "-"
            else:
                row["Intraday Signal"] = "-"; row["Intra Conf"] = 0; row["Confirm"] = "-"

            if d_sig in ("BUY","SELL") and d_lv:
                row["Entry"] = d_lv["entry"]; row["Stop Loss"] = d_lv["stop_loss"]
                row["Target"] = d_lv["target_1"]; row["R/R"] = round(d_lv["rr"], 1)
            else:
                row["Entry"] = None; row["Stop Loss"] = None; row["Target"] = None; row["R/R"] = None
            sd.append(row)
        except:
            sd.append({"Symbol": sym, "Live Price": None, "Close": None, "vs Close": None,
                "Daily Chg %": None, "Daily Signal": "Error", "Daily Conf": 0, "Conf_raw": 0,
                "RSI": None, "Supertrend": "-", "Ichimoku": "-", "Volume": None,
                "Intraday Signal": "-", "Intra Conf": 0, "Confirm": "-",
                "Entry": None, "Stop Loss": None, "Target": None, "R/R": None})
    pg.empty(); sta.empty()

    if sd:
        st.markdown("#### Filters")
        fc1, fc2, fc3, fc4 = st.columns(4)
        with fc1:
            all_sigs = sorted(set(s["Daily Signal"] for s in sd))
            sig_filter = st.multiselect("Daily Signal", all_sigs, default=all_sigs, key="f_sig")
        with fc2:
            all_st = sorted(set(s["Supertrend"] for s in sd if s["Supertrend"] != "-"))
            st_filter = st.multiselect("Supertrend", all_st, default=all_st, key="f_st")
        with fc3:
            if intraday_on:
                all_conf = sorted(set(s["Confirm"] for s in sd if s["Confirm"] != "-"))
                if all_conf:
                    conf_filter = st.multiselect("Confirmation", all_conf, default=all_conf, key="f_conf_type")
                else: conf_filter = []
            else:
                all_ichi = sorted(set(s["Ichimoku"] for s in sd if s["Ichimoku"] != "-"))
                ichi_filter = st.multiselect("Ichimoku", all_ichi, default=all_ichi, key="f_ichi")
        with fc4:
            min_conf = st.slider("Min Daily Conf %", 0, 100, 0, step=5, key="f_conf")

        fc5, fc6 = st.columns(2)
        with fc5:
            sort_opts = ["Symbol","Live Price","vs Close","Daily Chg %","Daily Signal","Daily Conf","RSI","R/R"]
            if intraday_on: sort_opts.append("Confirm")
            sort_by = st.selectbox("Sort by", sort_opts, index=0, key="f_sort")
        with fc6:
            sort_order = st.radio("Order", ["Ascending","Descending"], index=0, horizontal=True, key="f_order")

        filtered = sd
        filtered = [s for s in filtered if s["Daily Signal"] in sig_filter]
        filtered = [s for s in filtered if s["Supertrend"] in st_filter or s["Supertrend"] == "-"]
        if intraday_on and conf_filter:
            filtered = [s for s in filtered if s["Confirm"] in conf_filter or s["Confirm"] == "-"]
        elif not intraday_on:
            filtered = [s for s in filtered if s["Ichimoku"] in ichi_filter or s["Ichimoku"] == "-"]
        filtered = [s for s in filtered if s["Daily Conf"] >= min_conf]

        sort_asc = sort_order == "Ascending"
        try: filtered.sort(key=lambda x: (x[sort_by] is None, x[sort_by] if x[sort_by] is not None else 0), reverse=not sort_asc)
        except: pass

        st.caption(f"Showing **{len(filtered)}** of {len(sd)} tickers")

        disp = []
        for s in filtered:
            r = {"Symbol": s["Symbol"],
                 "Live": f"${s['Live Price']:.2f}" if s["Live Price"] else "-",
                 "Close": f"${s['Close']:.2f}" if s["Close"] else "-",
                 "vs Close": f"{s['vs Close']:+.2f}%" if s["vs Close"] is not None else "-",
                 "Chg": f"{s['Daily Chg %']:+.2f}%" if s["Daily Chg %"] is not None else "-",
                 "Daily": s["Daily Signal"],
                 "D.Conf": f"{s['Daily Conf']:.0f}%"}
            if intraday_on:
                r["Intraday"] = s["Intraday Signal"]
                r["I.Conf"] = f"{s['Intra Conf']:.0f}%"
                r["Confirm"] = s["Confirm"]
            r["RSI"] = f"{s['RSI']:.1f}" if s["RSI"] is not None else "-"
            r["ST"] = s["Supertrend"]
            r["Entry"] = f"${s['Entry']:.2f}" if s["Entry"] else "-"
            r["SL"] = f"${s['Stop Loss']:.2f}" if s["Stop Loss"] else "-"
            r["Target"] = f"${s['Target']:.2f}" if s["Target"] else "-"
            r["R/R"] = f"1:{s['R/R']:.1f}" if s["R/R"] else "-"
            disp.append(r)

        if disp: st.dataframe(pd.DataFrame(disp), use_container_width=True, hide_index=True)
        else: st.info("No tickers match filters.")

        c1,c2,c3,c4=st.columns(4)
        c1.metric("BUY",sum(1 for s in filtered if s["Daily Signal"]=="BUY"))
        c2.metric("SELL",sum(1 for s in filtered if s["Daily Signal"]=="SELL"))
        if intraday_on:
            c3.metric("CONFIRMED",sum(1 for s in filtered if "CONFIRMED" in s["Confirm"]))
        else:
            c3.metric("HOLD",sum(1 for s in filtered if s["Daily Signal"]=="HOLD"))
        c4.metric("Total",len(filtered))

        if filtered:
            export_df = pd.DataFrame(filtered).drop(columns=["Conf_raw"], errors="ignore")
            st.download_button("Export CSV", export_df.to_csv(index=False),
                             f"scanner_{datetime.now().strftime('%Y%m%d_%H%M')}.csv", "text/csv")


# ═══════════════════════════════════════════════════════════
# TAB 2: CHART ANALYSIS
# ═══════════════════════════════════════════════════════════
with tab2:
    st.header(f"{sel_sym} - Technical Analysis")
    try:
        # Chart interval selector
        chart_intervals = ["1m", "2m", "5m", "10m", "15m", "20m", "30m", "45m", "1h", "1d"]
        default_idx = chart_intervals.index(intra_interval) if intraday_on else 9
        ci1, ci2 = st.columns([3, 1])
        with ci1:
            chart_interval = st.select_slider("Chart Interval", options=chart_intervals, value=chart_intervals[default_idx], key="chart_int")
        with ci2:
            st.markdown(f"**Selected: {chart_interval}**")

        if chart_interval == "1d":
            chart_period = data_per
            chart_st_atr = SUPERTREND_ATR_PERIOD; chart_st_mult = SUPERTREND_MULTIPLIER
        elif chart_interval == "1h":
            chart_period = "60d"
            chart_st_atr = INTRA_ST_ATR; chart_st_mult = INTRA_ST_MULT
        elif chart_interval in ["1m", "2m"]:
            chart_period = "1d"
            chart_st_atr = INTRA_ST_ATR; chart_st_mult = INTRA_ST_MULT
        else:
            chart_period = "5d"
            chart_st_atr = INTRA_ST_ATR; chart_st_mult = INTRA_ST_MULT

        chart_label = f"{chart_interval}" if chart_interval != "1d" else "Daily"

        # Uses fetch_history (MultiIndex safe)
        df_chart = fetch_history(sel_sym, period=chart_period, interval=chart_interval)
        df_daily = fetch_history(sel_sym, period="90d", interval="1d")

        if len(df_chart) >= 30 and len(df_daily) >= 55:
            df_chart = calculate_indicators(df_chart, st_atr_period=chart_st_atr, st_multiplier=chart_st_mult)
            df_daily = calculate_indicators(df_daily)
            live_p, _ = get_live_price(sel_sym)
            d_sig, d_conf, d_lv = quick_signal_with_levels(df_daily, SIGNAL_THRESHOLD, live_p)
            la_d = df_daily.iloc[-1]
            std = "Bullish" if pd.notna(la_d["ST_Direction"]) and la_d["ST_Direction"]==1 else "Bearish"

            mc = st.columns(7)
            mc[0].metric("Close", f"${float(la_d['Close']):.2f}")
            if live_p:
                vs_c = round((live_p - float(la_d["Close"])) / float(la_d["Close"]) * 100, 2)
                mc[1].metric("Live", f"${live_p:.2f}", f"{vs_c:+.2f}%")
            else: mc[1].metric("Live", "-")
            mc[2].metric("Daily Signal", d_sig)
            mc[3].metric("RSI", f"{la_d['RSI']:.1f}")
            mc[4].metric("Conf", f"{d_conf:.0%}")
            mc[5].metric("VWAP", f"${la_d['VWAP']:.2f}" if pd.notna(la_d["VWAP"]) else "-")
            mc[6].metric("Supertrend", std)

            if intraday_on and len(df_chart) >= 55:
                i_sig, i_conf = compute_signal_score(df_chart, INTRA_THRESHOLD)
                ic1, ic2, ic3 = st.columns(3)
                ic1.metric(f"Intraday Signal ({intra_interval})", i_sig)
                ic2.metric("Intra Conf", f"{i_conf:.0%}")
                if d_sig == i_sig and d_sig in ("BUY","SELL"):
                    ic3.metric("Confirmation", f"CONFIRMED {d_sig}")
                    st.success(f"Both daily and intraday agree: {d_sig}")
                elif d_sig in ("BUY","SELL"):
                    ic3.metric("Confirmation", "DAILY ONLY")
                    st.warning(f"Daily says {d_sig}, intraday says {i_sig} — wait for confirmation")

            if d_sig in ("BUY","SELL") and d_lv:
                st.subheader("Position Levels" + (" (live price)" if live_p else ""))
                lc1,lc2,lc3,lc4,lc5=st.columns(5)
                lc1.metric("Entry",f"${d_lv['entry']:.2f}")
                lc2.metric("Stop Loss",f"${d_lv['stop_loss']:.2f}",f"-{d_lv['risk_pct']:.1f}%",delta_color="inverse")
                lc3.metric("Target 1",f"${d_lv['target_1']:.2f}")
                lc4.metric("Target 2",f"${d_lv['target_2']:.2f}")
                lc5.metric("R/R",f"1:{d_lv['rr']:.1f}")

            st.subheader(f"Candlestick Chart \u2014 {chart_label}")
            fig = create_candlestick_chart(df_chart, sel_sym, chart_label)
            st.plotly_chart(fig, use_container_width=True)

            st.subheader("Ichimoku Cloud (Daily)")
            ic2=df_daily[["Close","Tenkan","Kijun","Senkou_A","Senkou_B"]].copy()
            ic2.columns=["Close","Tenkan","Kijun","Senkou A","Senkou B"]; st.line_chart(ic2)

            st.subheader("RSI (Daily)"); st.line_chart(df_daily[["RSI"]])

            st.subheader("MACD (Daily)")
            mc2=df_daily[["MACD_line","MACD_signal","MACD_hist"]].copy()
            mc2.columns=["MACD","Signal","Histogram"]; st.line_chart(mc2)

        else: st.warning("Insufficient data")
    except Exception as e: st.error(f"Error: {e}")


# ═══════════════════════════════════════════════════════════
# TAB 3: SIGNAL HISTORY
# ═══════════════════════════════════════════════════════════
with tab3:
    st.header("Signal History"); h=load_signal_history()
    if h:
        hd=pd.DataFrame(h); sf=st.multiselect("Filter",["BUY","SELL"],default=["BUY","SELL"])
        fl=hd[hd["signal"].isin(sf)]
        if not fl.empty:
            dc=["timestamp","symbol","signal","price","confidence"]
            av=[c for c in dc if c in fl.columns]
            st.dataframe(fl[av].sort_values("timestamp",ascending=False),use_container_width=True,hide_index=True)
    else: st.info("No history yet.")


# ═══════════════════════════════════════════════════════════
# TAB 4: BACKTEST
# ═══════════════════════════════════════════════════════════
with tab4:
    st.header("Backtest")
    st.caption(f"{bts} | {btp} | ${btc:,.0f} | Threshold: {SIGNAL_THRESHOLD:.0%}")
    rb=st.button("Run Backtest",type="primary",use_container_width=True)
    if rb:
        with st.spinner(f"Backtesting {bts}..."):
            try:
                dbt,tbt,mbt,ddbt=run_full_backtest(bts,btp,btc,SIGNAL_THRESHOLD,SUPERTREND_ATR_PERIOD,SUPERTREND_MULTIPLIER)
                if dbt is None: st.error("Insufficient data.")
                else:
                    st.subheader("Performance")
                    c1,c2,c3,c4,c5,c6=st.columns(6)
                    c1.metric("Strategy",f"{mbt['Total Return (%)']:+.2f}%")
                    c2.metric("Buy&Hold",f"{mbt['Buy & Hold Return (%)']:+.2f}%")
                    c3.metric("Sharpe",f"{mbt['Sharpe Ratio']:.2f}")
                    c4.metric("Max DD",f"{mbt['Max Drawdown (%)']:.2f}%")
                    c5.metric("Win Rate",f"{mbt['Win Rate (%)']:.1f}%")
                    c6.metric("Trades",f"{mbt['Total Trades']}")
                    with st.expander("All Metrics"):
                        for k,v in mbt.items(): st.text(f"{k}: {v}")
                    sr=mbt["Total Return (%)"]; bh=mbt["Buy & Hold Return (%)"]
                    if sr>bh: st.success(f"OUTPERFORMS by {sr-bh:.2f}%")
                    elif sr<bh: st.warning(f"UNDERPERFORMS by {bh-sr:.2f}%")
                    st.subheader("Equity Curve")
                    eq=dbt[["Portfolio","BuyHold"]].copy(); eq.columns=["Strategy","Buy & Hold"]; st.line_chart(eq)
                    st.subheader("Drawdown"); st.area_chart(pd.DataFrame({"DD (%)":ddbt.values},index=dbt.index))
                    st.subheader("Monthly Returns (%)")
                    dr=dbt["Portfolio"].pct_change(); mr=dr.resample("ME").apply(lambda x:(1+x).prod()-1)*100
                    md=pd.DataFrame({"Year":mr.index.year,"Month":mr.index.month,"Return":mr.values})
                    pv=md.pivot_table(values="Return",index="Year",columns="Month",aggfunc="sum")
                    mn=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
                    pv.columns=[mn[c-1] for c in pv.columns]
                    def cr(v):
                        if pd.isna(v): return ""
                        i=min(abs(v)/10,1.0)
                        return f"background-color:rgba(76,175,80,{i:.2f})" if v>0 else f"background-color:rgba(244,67,54,{i:.2f})"
                    st.dataframe(pv.style.map(cr).format("{:.1f}%",na_rep="-"),use_container_width=True)
                    st.subheader(f"Trades ({len(tbt)})")
                    if tbt:
                        td=pd.DataFrame(tbt)
                        def cre(v):
                            if v=="WIN": return "color:#4CAF50;font-weight:bold"
                            elif v=="LOSS": return "color:#F44336;font-weight:bold"
                            return ""
                        def cp(v):
                            try: return "color:#4CAF50" if v>0 else ("color:#F44336" if v<0 else "")
                            except: return ""
                        st.dataframe(td.style.map(cre,subset=["Result"]).map(cp,subset=["P&L ($)","P&L (%)"]),use_container_width=True,hide_index=True)
                        st.download_button("Download CSV",td.to_csv(index=False),f"bt_{bts}_{btp}.csv","text/csv")
            except Exception as e: st.error(f"Failed: {e}"); st.exception(e)
    else:
        st.info("Configure in sidebar, click **Run Backtest**.")


# ═══════════════════════════════════════════════════════════
# TAB 5: NEWS
# ═══════════════════════════════════════════════════════════

with tab5:
    st.header("Market News")

    # News source selector
    nc1, nc2 = st.columns([2, 1])
    with nc1:
        news_sym = st.selectbox("News for ticker", ["GENERAL"] + WATCHLIST, index=0, key="news_sym")
    with nc2:
        max_news = st.slider("Max articles", 5, 30, 10, key="news_max")

    if st.button("Fetch News", type="primary", use_container_width=True, key="fetch_news"):
        with st.spinner("Fetching latest news..."):
            try:
                if news_sym == "GENERAL":
                    # Get news from SPY as proxy for general market
                    tickers_for_news = ["SPY", "QQQ", "DIA"]
                    all_news = []
                    for t in tickers_for_news:
                        try:
                            tk = yf.Ticker(t)
                            news = tk.news
                            if news:
                                all_news.extend(news)
                        except:
                            pass
                else:
                    tk = yf.Ticker(news_sym)
                    all_news = tk.news if tk.news else []

                if all_news:
                    # Sort by publish date (newest first)
                    seen_titles = set()
                    unique_news = []
                    for item in all_news:
                        content = item.get("content", item)
                        title = content.get("title", item.get("title", ""))
                        if title and title not in seen_titles:
                            seen_titles.add(title)
                            unique_news.append(item)

                    unique_news = unique_news[:max_news]

                    for i, item in enumerate(unique_news):
                        content = item.get("content", item)
                        title = content.get("title", item.get("title", "No title"))
                        pub_date = content.get("pubDate", item.get("pubDate", ""))
                        link = content.get("url", item.get("link", ""))
                        source = content.get("provider", {})
                        if isinstance(source, dict):
                            source_name = source.get("displayName", "Unknown")
                        elif isinstance(source, list) and source:
                            source_name = source[0].get("displayName", "Unknown")
                        else:
                            source_name = "Unknown"
                        summary = content.get("summary", item.get("summary", ""))

                        # Display
                        with st.container():
                            st.markdown(f"**{i+1}. {title}**")
                            col_a, col_b = st.columns([3, 1])
                            with col_a:
                                if summary:
                                    st.caption(summary[:200] + "..." if len(summary) > 200 else summary)
                            with col_b:
                                st.caption(f"Source: {source_name}")
                                if pub_date:
                                    st.caption(f"{pub_date[:19]}")
                            if link:
                                st.markdown(f"[Read full article]({link})")
                            st.divider()
                else:
                    st.info(f"No news found for {news_sym}")

            except Exception as e:
                st.error(f"Error fetching news: {e}")
    else:
        st.info("Select a ticker and click **Fetch News** to load latest headlines.")
        st.markdown("""
        **Tips:**
        - Select **GENERAL** for broad market news (SPY/QQQ/DIA)
        - Select a specific ticker for company-specific news
        - Check news **before entering trades** — especially on CPI/FOMC days
        - yfinance provides headlines from Yahoo Finance sources
        """)
        
if ar: time.sleep(60); st.rerun()
