#!/usr/bin/env python3
"""
=============================================================
  TRADING SIGNAL BOT v1.8 (Configurable Threshold + Levels)
  8 indicators + Entry/SL/Target + adjustable threshold
  Config shared with dashboard via bot_config.json
  Author : Lemon Leong (generated by Copilot)
  Date   : 2026-05-15
=============================================================
"""

import json, os, time, logging
from datetime import datetime, timedelta
import numpy as np, pandas as pd
import yfinance as yf

# ── FIX: Corporate SSL (Micron network) ─────────────────
from curl_cffi import requests as _curl_requests
_original_init = _curl_requests.Session.__init__
def _patched_init(self, *args, **kwargs):
    kwargs["verify"] = False
    _original_init(self, *args, **kwargs)
_curl_requests.Session.__init__ = _patched_init
import warnings
warnings.filterwarnings("ignore", message=".*Unverified HTTPS.*")
# ─────────────────────────────────────────────────────────

# ── CONFIG FILES ───────────────────────────────────────────

CONFIG_FILE = "bot_config.json"
WATCHLIST_FILE = "watchlist.json"

DEFAULT_CONFIG = {
    "signal_threshold": 0.8,
    "supertrend_atr_period": 10,
    "supertrend_multiplier": 3.0,
}

DEFAULT_WATCHLIST = ["ADM","DE","MOS","CF","WEAT","DBA","FSLR","ENPH","AWK","XLU","AAPL","MSFT","NVDA","TSLA","SPY"]


def load_config():
    """Load bot config from bot_config.json, fallback to defaults."""
    config = DEFAULT_CONFIG.copy()
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f:
                saved = json.load(f)
                config.update(saved)
        except (json.JSONDecodeError, IOError):
            pass
    return config


def load_watchlist():
    if os.path.exists(WATCHLIST_FILE):
        try:
            with open(WATCHLIST_FILE, "r") as f:
                data = json.load(f)
                if isinstance(data, list) and len(data) > 0:
                    t = [x.upper().strip() for x in data if x.strip()]
                    if t: return t
        except: pass
    return DEFAULT_WATCHLIST.copy()


# Load initial config
config = load_config()
WATCHLIST = load_watchlist()

# Fixed parameters
EMA_FAST=9; EMA_SLOW=21; RSI_PERIOD=14
RSI_BUY_RANGE=(40,70); RSI_SELL_RANGE=(30,60)
MACD_FAST=12; MACD_SLOW=26; MACD_SIGNAL=9
BB_PERIOD=20; BB_STD=2; VOLUME_MA_PERIOD=20
ICHIMOKU_TENKAN=9; ICHIMOKU_KIJUN=26; ICHIMOKU_SENKOU_B=52

# Configurable parameters (loaded from bot_config.json)
SIGNAL_THRESHOLD = config["signal_threshold"]
SUPERTREND_ATR_PERIOD = config["supertrend_atr_period"]
SUPERTREND_MULTIPLIER = config["supertrend_multiplier"]

SCAN_INTERVAL=14400; DATA_PERIOD="90d"; DATA_INTERVAL="1d"
SIGNALS_LOG = "signals_history.json"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler("trading_bot.log"), logging.StreamHandler()])
logger = logging.getLogger(__name__)

# ── TECHNICAL INDICATORS ───────────────────────────────────

def calculate_indicators(df):
    df = df.copy()
    df["EMA_fast"] = df["Close"].ewm(span=EMA_FAST, adjust=False).mean()
    df["EMA_slow"] = df["Close"].ewm(span=EMA_SLOW, adjust=False).mean()
    delta = df["Close"].diff()
    gain = delta.where(delta > 0, 0.0); loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.ewm(com=RSI_PERIOD-1, min_periods=RSI_PERIOD).mean()
    avg_loss = loss.ewm(com=RSI_PERIOD-1, min_periods=RSI_PERIOD).mean()
    rs = avg_gain / avg_loss; df["RSI"] = 100 - (100 / (1 + rs))
    ema_fm = df["Close"].ewm(span=MACD_FAST, adjust=False).mean()
    ema_sm = df["Close"].ewm(span=MACD_SLOW, adjust=False).mean()
    df["MACD_line"] = ema_fm - ema_sm
    df["MACD_signal"] = df["MACD_line"].ewm(span=MACD_SIGNAL, adjust=False).mean()
    df["MACD_hist"] = df["MACD_line"] - df["MACD_signal"]
    df["BB_middle"] = df["Close"].rolling(BB_PERIOD).mean()
    bb_std = df["Close"].rolling(BB_PERIOD).std()
    df["BB_upper"] = df["BB_middle"] + BB_STD * bb_std
    df["BB_lower"] = df["BB_middle"] - BB_STD * bb_std
    df["Volume_MA"] = df["Volume"].rolling(VOLUME_MA_PERIOD).mean()
    tp = (df["High"] + df["Low"] + df["Close"]) / 3
    df["VWAP"] = (tp * df["Volume"]).cumsum() / df["Volume"].cumsum()
    h9 = df["High"].rolling(ICHIMOKU_TENKAN).max(); l9 = df["Low"].rolling(ICHIMOKU_TENKAN).min()
    df["Tenkan"] = (h9 + l9) / 2
    h26 = df["High"].rolling(ICHIMOKU_KIJUN).max(); l26 = df["Low"].rolling(ICHIMOKU_KIJUN).min()
    df["Kijun"] = (h26 + l26) / 2
    df["Senkou_A"] = ((df["Tenkan"] + df["Kijun"]) / 2).shift(ICHIMOKU_KIJUN)
    h52 = df["High"].rolling(ICHIMOKU_SENKOU_B).max(); l52 = df["Low"].rolling(ICHIMOKU_SENKOU_B).min()
    df["Senkou_B"] = ((h52 + l52) / 2).shift(ICHIMOKU_KIJUN)
    hl2 = (df["High"] + df["Low"]) / 2
    high_low = df["High"] - df["Low"]
    high_close = (df["High"] - df["Close"].shift()).abs()
    low_close = (df["Low"] - df["Close"].shift()).abs()
    true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    atr_st = true_range.rolling(SUPERTREND_ATR_PERIOD).mean()
    upper_band = hl2 + SUPERTREND_MULTIPLIER * atr_st
    lower_band = hl2 - SUPERTREND_MULTIPLIER * atr_st
    supertrend = pd.Series(index=df.index, dtype=float)
    direction = pd.Series(index=df.index, dtype=float)
    supertrend.iloc[0] = upper_band.iloc[0]; direction.iloc[0] = -1
    for i in range(1, len(df)):
        if pd.isna(upper_band.iloc[i]) or pd.isna(lower_band.iloc[i]):
            supertrend.iloc[i] = supertrend.iloc[i-1]; direction.iloc[i] = direction.iloc[i-1]; continue
        fl = lower_band.iloc[i] if (lower_band.iloc[i] > lower_band.iloc[i-1] or df["Close"].iloc[i-1] < lower_band.iloc[i-1]) else lower_band.iloc[i-1]
        fu = upper_band.iloc[i] if (upper_band.iloc[i] < upper_band.iloc[i-1] or df["Close"].iloc[i-1] > upper_band.iloc[i-1]) else upper_band.iloc[i-1]
        if supertrend.iloc[i-1] == fu:
            if df["Close"].iloc[i] > fu: supertrend.iloc[i] = fl; direction.iloc[i] = 1
            else: supertrend.iloc[i] = fu; direction.iloc[i] = -1
        else:
            if df["Close"].iloc[i] < fl: supertrend.iloc[i] = fu; direction.iloc[i] = -1
            else: supertrend.iloc[i] = fl; direction.iloc[i] = 1
    df["Supertrend"] = supertrend; df["ST_Direction"] = direction
    return df


def generate_signal(df, symbol):
    if len(df) < 55:
        return {"symbol": symbol, "signal": "INSUFFICIENT_DATA", "confidence": 0}
    latest = df.iloc[-1]; prev = df.iloc[-2]
    ema_bullish = latest["EMA_fast"] > latest["EMA_slow"]
    ema_bearish = latest["EMA_fast"] < latest["EMA_slow"]
    ema_cross_up = (prev["EMA_fast"] <= prev["EMA_slow"]) and ema_bullish
    ema_cross_down = (prev["EMA_fast"] >= prev["EMA_slow"]) and ema_bearish
    rsi = latest["RSI"]
    rsi_buy_ok = RSI_BUY_RANGE[0] <= rsi <= RSI_BUY_RANGE[1]
    rsi_sell_ok = RSI_SELL_RANGE[0] <= rsi <= RSI_SELL_RANGE[1]
    macd_bullish = latest["MACD_hist"] > 0; macd_bearish = latest["MACD_hist"] < 0
    bb_not_upper = latest["Close"] < latest["BB_upper"] * 0.99
    bb_not_lower = latest["Close"] > latest["BB_lower"] * 1.01
    vol_above_avg = latest["Volume"] > latest["Volume_MA"] if latest["Volume_MA"] > 0 else False
    vwap_bullish = latest["Close"] > latest["VWAP"] if pd.notna(latest["VWAP"]) else False
    vwap_bearish = latest["Close"] < latest["VWAP"] if pd.notna(latest["VWAP"]) else False
    ichi_ok = pd.notna(latest["Senkou_A"]) and pd.notna(latest["Senkou_B"]) and pd.notna(latest["Tenkan"]) and pd.notna(latest["Kijun"])
    if ichi_ok:
        cloud_top = max(latest["Senkou_A"], latest["Senkou_B"])
        cloud_bottom = min(latest["Senkou_A"], latest["Senkou_B"])
        ichimoku_bullish = (latest["Close"] > cloud_top) and (latest["Tenkan"] > latest["Kijun"])
        ichimoku_bearish = (latest["Close"] < cloud_bottom) and (latest["Tenkan"] < latest["Kijun"])
    else:
        ichimoku_bullish = False; ichimoku_bearish = False; cloud_top = 0; cloud_bottom = 0
    st_bullish = latest["ST_Direction"] == 1 if pd.notna(latest["ST_Direction"]) else False
    st_bearish = latest["ST_Direction"] == -1 if pd.notna(latest["ST_Direction"]) else False
    st_val = latest["Supertrend"] if pd.notna(latest["Supertrend"]) else 0

    buy_score = sum([ema_bullish,rsi_buy_ok,macd_bullish,bb_not_upper,vol_above_avg,vwap_bullish,ichimoku_bullish,st_bullish]) / 8
    sell_score = sum([ema_bearish,rsi_sell_ok,macd_bearish,bb_not_lower,vol_above_avg,vwap_bearish,ichimoku_bearish,st_bearish]) / 8

    signal = "HOLD"; confidence = 0.0; reasons = []; levels = {}
    entry = round(latest["Close"], 2)

    if buy_score >= SIGNAL_THRESHOLD:
        signal = "BUY"; confidence = buy_score
        if ema_cross_up: reasons.append("EMA 9/21 CROSSOVER UP"); confidence = min(1.0, confidence+0.1)
        else: reasons.append("EMA bullish trend")
        if rsi_buy_ok: reasons.append(f"RSI {rsi:.1f} (momentum zone)")
        if macd_bullish: reasons.append(f"MACD histogram +{latest['MACD_hist']:.3f}")
        if bb_not_upper: reasons.append("Below upper BB (room to run)")
        if vol_above_avg: reasons.append("Volume above 20-day avg")
        if vwap_bullish: reasons.append(f"Price above VWAP (${latest['VWAP']:.2f})")
        if ichimoku_bullish: reasons.append("Above Ichimoku Cloud + TK bullish")
        if st_bullish: reasons.append(f"Supertrend bullish (${st_val:.2f})")
        sl = round(st_val,2) if (pd.notna(st_val) and st_val>0 and st_val<entry) else round(latest["BB_lower"],2)
        risk = entry - sl
        if risk <= 0: risk = entry*0.02; sl = round(entry-risk,2)
        t1 = round(latest["BB_upper"],2); t2 = round(entry+2*risk,2)
        levels = {"entry":entry,"stop_loss":sl,"target_1":t1,"target_2":t2,
                  "risk_pct":round((entry-sl)/entry*100,2),"reward_1_pct":round((t1-entry)/entry*100,2),
                  "reward_2_pct":round((t2-entry)/entry*100,2),"rr_ratio":round((t1-entry)/risk,2) if risk>0 else 0,"type":"LONG"}

    elif sell_score >= SIGNAL_THRESHOLD:
        signal = "SELL"; confidence = sell_score
        if ema_cross_down: reasons.append("EMA 9/21 CROSSOVER DOWN"); confidence = min(1.0, confidence+0.1)
        else: reasons.append("EMA bearish trend")
        if rsi_sell_ok: reasons.append(f"RSI {rsi:.1f} (weakness zone)")
        if macd_bearish: reasons.append(f"MACD histogram {latest['MACD_hist']:.3f}")
        if bb_not_lower: reasons.append("Above lower BB (room to fall)")
        if vol_above_avg: reasons.append("Volume above 20-day avg")
        if vwap_bearish: reasons.append(f"Price below VWAP (${latest['VWAP']:.2f})")
        if ichimoku_bearish: reasons.append("Below Ichimoku Cloud + TK bearish")
        if st_bearish: reasons.append(f"Supertrend bearish (${st_val:.2f})")
        sl = round(st_val,2) if (pd.notna(st_val) and st_val>0 and st_val>entry) else round(latest["BB_upper"],2)
        risk = sl - entry
        if risk <= 0: risk = entry*0.02; sl = round(entry+risk,2)
        t1 = round(latest["BB_lower"],2); t2 = round(entry-2*risk,2)
        levels = {"entry":entry,"stop_loss":sl,"target_1":t1,"target_2":t2,
                  "risk_pct":round((sl-entry)/entry*100,2),"reward_1_pct":round((entry-t1)/entry*100,2),
                  "reward_2_pct":round((entry-t2)/entry*100,2),"rr_ratio":round((entry-t1)/risk,2) if risk>0 else 0,"type":"SHORT"}

    return {"symbol":symbol,"signal":signal,"confidence":round(confidence,2),"price":entry,"reasons":reasons,"levels":levels,
        "indicators":{"EMA_fast":round(latest["EMA_fast"],2),"EMA_slow":round(latest["EMA_slow"],2),
            "RSI":round(rsi,2),"MACD_hist":round(latest["MACD_hist"],4),
            "BB_upper":round(latest["BB_upper"],2),"BB_lower":round(latest["BB_lower"],2),
            "VWAP":round(latest["VWAP"],2) if pd.notna(latest["VWAP"]) else 0,
            "Tenkan":round(latest["Tenkan"],2) if pd.notna(latest["Tenkan"]) else 0,
            "Kijun":round(latest["Kijun"],2) if pd.notna(latest["Kijun"]) else 0,
            "Cloud_Top":round(cloud_top,2) if ichi_ok else 0,"Cloud_Bottom":round(cloud_bottom,2) if ichi_ok else 0,
            "Supertrend":round(st_val,2),"ST_Direction":"Bullish" if st_bullish else "Bearish",
            "Volume":int(latest["Volume"]),"Volume_MA":int(latest["Volume_MA"])},
        "timestamp":datetime.now().strftime("%Y-%m-%d %H:%M:%S")}


def print_signal(sig):
    if sig["signal"] not in ("BUY","SELL"): return
    ind = sig["indicators"]; lv = sig["levels"]
    cb = "=" * int(sig["confidence"]*10) + "-" * (10 - int(sig["confidence"]*10))
    print()
    print("  " + "=" * 60)
    print(f"  [{sig['signal']}] {sig['symbol']} @ ${sig['price']:,.2f}  [{cb}] {sig['confidence']:.0%}")
    print("  " + "-" * 60)
    for r in sig["reasons"]: print(f"    > {r}")
    print("  " + "-" * 60)
    print(f"    POSITION LEVELS ({lv['type']}):")
    print(f"    {'Entry:':14s} ${lv['entry']:>10,.2f}")
    print(f"    {'Stop Loss:':14s} ${lv['stop_loss']:>10,.2f}  (risk: -{lv['risk_pct']:.1f}%)")
    print(f"    {'Target 1:':14s} ${lv['target_1']:>10,.2f}  (reward: +{lv['reward_1_pct']:.1f}%)  <- BB band")
    print(f"    {'Target 2:':14s} ${lv['target_2']:>10,.2f}  (reward: +{lv['reward_2_pct']:.1f}%)  <- 2:1 R/R")
    print(f"    {'Risk/Reward:':14s} 1:{lv['rr_ratio']:.1f}")
    print("  " + "-" * 60)
    print(f"    EMA 9: {ind['EMA_fast']} | EMA 21: {ind['EMA_slow']}")
    print(f"    RSI: {ind['RSI']}  |  MACD: {ind['MACD_hist']}")
    print(f"    BB: [{ind['BB_lower']} - {ind['BB_upper']}]  |  VWAP: {ind['VWAP']}")
    print(f"    Ichimoku: [{ind['Cloud_Bottom']} - {ind['Cloud_Top']}]")
    print(f"    Supertrend: {ind['Supertrend']} ({ind['ST_Direction']})")
    print(f"    Volume: {ind['Volume']:,} (Avg: {ind['Volume_MA']:,})")
    print("  " + "=" * 60)


def print_scan_summary(signals):
    buys = [s for s in signals if s["signal"]=="BUY"]
    sells = [s for s in signals if s["signal"]=="SELL"]
    holds = [s for s in signals if s["signal"]=="HOLD"]
    print()
    print("  " + "=" * 60)
    print(f"  SCAN SUMMARY — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Tickers: {len(signals)} | Threshold: {SIGNAL_THRESHOLD} ({int(SIGNAL_THRESHOLD*8)}/8 needed)")
    print("  " + "=" * 60)
    if buys:
        print(f"  BUY:  {len(buys)}")
        print(f"  {'Symbol':>10s} {'Price':>10s} {'Conf':>6s} {'Entry':>10s} {'Stop Loss':>10s} {'Target':>10s} {'R/R':>5s}")
        for s in buys:
            lv = s["levels"]
            print(f"  {s['symbol']:>10s} ${s['price']:>9,.2f} {s['confidence']:>5.0%} ${lv['entry']:>9,.2f} ${lv['stop_loss']:>9,.2f} ${lv['target_1']:>9,.2f} 1:{lv['rr_ratio']:.1f}")
    if sells:
        print(f"  SELL: {len(sells)}")
        print(f"  {'Symbol':>10s} {'Price':>10s} {'Conf':>6s} {'Entry':>10s} {'Stop Loss':>10s} {'Target':>10s} {'R/R':>5s}")
        for s in sells:
            lv = s["levels"]
            print(f"  {s['symbol']:>10s} ${s['price']:>9,.2f} {s['confidence']:>5.0%} ${lv['entry']:>9,.2f} ${lv['stop_loss']:>9,.2f} ${lv['target_1']:>9,.2f} 1:{lv['rr_ratio']:.1f}")
    print(f"  HOLD: {len(holds)}")
    if holds: print(f"         {', '.join([s['symbol'] for s in holds])}")
    print("  " + "=" * 60)


def save_signals(signals):
    history = []
    if os.path.exists(SIGNALS_LOG):
        try:
            with open(SIGNALS_LOG, "r") as f: history = json.load(f)
        except: history = []
    actionable = [s for s in signals if s["signal"] in ("BUY","SELL")]
    history.extend(actionable); history = history[-500:]
    with open(SIGNALS_LOG, "w") as f: json.dump(history, f, indent=2, default=str)
    logger.info(f"Saved {len(actionable)} signals")


def run_scan():
    global WATCHLIST, SIGNAL_THRESHOLD, SUPERTREND_ATR_PERIOD, SUPERTREND_MULTIPLIER
    WATCHLIST = load_watchlist()
    config = load_config()
    SIGNAL_THRESHOLD = config["signal_threshold"]
    SUPERTREND_ATR_PERIOD = config["supertrend_atr_period"]
    SUPERTREND_MULTIPLIER = config["supertrend_multiplier"]

    logger.info("=" * 60)
    logger.info(f"Scan at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info(f"Watchlist: {len(WATCHLIST)} | Threshold: {SIGNAL_THRESHOLD} ({int(SIGNAL_THRESHOLD*8)}/8)")
    logger.info(f"Supertrend: ATR={SUPERTREND_ATR_PERIOD}, Mult={SUPERTREND_MULTIPLIER}")
    logger.info("=" * 60)
    all_signals = []
    for symbol in WATCHLIST:
        try:
            logger.info(f"Scanning {symbol}...")
            df = yf.Ticker(symbol).history(period=DATA_PERIOD, interval=DATA_INTERVAL)
            if df.empty or len(df) < 55:
                logger.warning(f"{symbol}: Insufficient data"); continue
            df = calculate_indicators(df)
            sig = generate_signal(df, symbol)
            all_signals.append(sig)
            if sig["signal"] in ("BUY","SELL"):
                logger.info(f"{sig['signal']} -> {sig['symbol']} @ ${sig['price']} ({sig['confidence']:.0%})")
                print_signal(sig)
        except Exception as e:
            logger.error(f"Error {symbol}: {e}"); continue
    if all_signals:
        print_scan_summary(all_signals); save_signals(all_signals)
    logger.info(f"Done. {len(all_signals)} tickers. View: http://localhost:8501")
    return all_signals


def main():
    print()
    print("  " + "=" * 60)
    print("  TRADING SIGNAL BOT v1.8 (Configurable Threshold)")
    print("  " + "=" * 60)
    print(f"  Indicators:  EMA+RSI+MACD+BB+Vol+VWAP+Ichimoku+Supertrend")
    print(f"  Threshold:   {SIGNAL_THRESHOLD} (need {int(SIGNAL_THRESHOLD*8)}/8)")
    print(f"  Supertrend:  ATR={SUPERTREND_ATR_PERIOD}, Multiplier={SUPERTREND_MULTIPLIER}")
    print(f"  Levels:      Entry / Stop Loss / Target 1 / Target 2")
    print(f"  Config:      {CONFIG_FILE} (edit via dashboard sidebar)")
    print(f"  Scan:        Every {SCAN_INTERVAL//3600}h")
    print(f"  Watchlist:   {len(WATCHLIST)} tickers")
    print(f"  Dashboard:   http://localhost:8501")
    print("  " + "=" * 60)
    print()
    logger.info("Bot v1.8 started!")
    while True:
        try: run_scan()
        except Exception as e: logger.error(f"Scan failed: {e}")
        logger.info(f"Sleeping {SCAN_INTERVAL//3600}h...")
        print(f"\n  Next scan in {SCAN_INTERVAL//3600}h. Ctrl+C to stop.\n")
        time.sleep(SCAN_INTERVAL)

if __name__ == "__main__":
    main()
